import React from "react";  // import React (to provide access to TSX)
import { useState } from 'react'
import './photoviewer.css'

//Remember that this file is a Component - it's not just functions...
// it's everything we need to get data and then load a part of a page

//creates an array of imageURLs from picsum.photos
const brokenImages = [
    1, 24, 32, 36, 44, 47
];
export function getImageUrls() {
    const urls = [];
    for (let i = 0; i < 50; i++) {
        if (!brokenImages.includes(i)) {
            const imageNumberString = i.toString().padStart(2, '0');
            urls.push(`https://picsum.photos/id/6${imageNumberString}/1600/900.jpg`)
        }
    }
    return urls;
}

//renders a list of small images from the urls generated by getImageUrls
//props: {key: type, key:type} is used to define the parameters that the func will take
// the parameters all come into the function as properties of the props object}
export function SecondaryPhotos(props: {
    srcArray: string[];
    //React.Dispatch... is used here to pass a setState as a parameter 
    setImageUrl: React.Dispatch<React.SetStateAction<string>>;
    imageUrl: string;
}) {
    //a setState must be called within a function 
    const [isSelectedImage, setSelectedImage] = useState("");

    // this function simply takes the SetState parameter we passed in earlier, and uses it within a subfunction unique to this function (i.e. SecondaryPhotos())
    function handleClick(x: string) {

        //Parameters passed into a component function are part of the props object, so we need to call props.myVariable...
        props.setImageUrl(x);
        setSelectedImage(x);
    }

    return (
        <div className='secondary-image-container'>
            {props.srcArray.map((el) =>
                <img src={el}
                    className={`secondary-image ${el === isSelectedImage ? 'selected-secondary-image' : ""}`} id={el}
                    onClick={() => handleClick(el)} //n.b. onClick must take a function in this format i.e. 'do this'
                ></img>)}
        </div>);
}



// export function ImageSelector() {


//     return (
//         <div>
//             {/* The selected image is {imageUrl}
//             <img className="secondary-image" src={imageUrl}></img> */}
//             <SecondaryPhotos srcArray={imageUrls} />
//         </div>
//     );


// }
